language: go

services:
  - docker

sudo: required

go:
  - 1.8

install:
  - make
  - go get github.com/mattn/goveralls

script:
  - make unit-test
  - goveralls -repotoken=${COVERALLS_REPO_TOKEN} -service=travis-ci
