language: go

services:
  - docker

sudo: required

go:
  - 1.8

install:
  - make
  - go get github.com/mattn/goveralls

script:
  - make unit-tests
  - make integration-tests
  - goveralls -repotoken=${COVERALLS_REPO_TOKEN} -flags=--tags=integration -service=travis-ci
